package es.sebas1705.mappers

import es.sebas1705.domain.model.stats.SurveyModel
import es.sebas1705.firestore.documents.SurveyDocument
import es.sebas1705.models.stats.Opinion
import es.sebas1705.resources.games.Languages
import es.sebas1705.room.entities.SurveyEntity

private fun op(points: Int, opinion: String) = Opinion(points, opinion)

fun SurveyDocument.toSurveyModel() = SurveyModel(
    authorFirebaseId = authorFirebaseId,
    authorNickName = authorNickName,
    authorAge = authorAge,
    profession = profession,
    language = Languages.entries[language],
    androidKnowing = androidKnowing,
    applicationsKnowing = applicationsKnowing,
    gamesKnowing = gamesKnowing,
    socialNetworksKnowing = socialNetworksKnowing,
    otherKnowing = otherKnowing,
    predictionOpinion = op(predictionPoints, predictionOpinion),
    synthesisOpinion = op(synthesisPoints, synthesisOpinion),
    familiarityOpinion = op(familiarityPoints, familiarityOpinion),
    generalityOpinion = op(generalityPoints, generalityOpinion),
    consistencyOpinion = op(consistencyPoints, consistencyOpinion),
    learnabilityGeneralOpinion = op(learnabilityGeneralPoints, learnabilityGeneralOpinion),
    dialogInitiativeOpinion = op(dialogInitiativePoints, dialogInitiativeOpinion),
    multitaskingOpinion = op(multitaskingPoints, multitaskingOpinion),
    taskControlOpinion = op(taskControlPoints, taskControlOpinion),
    adaptationOpinion = op(adaptationPoints, adaptationOpinion),
    substitutionOpinion = op(substitutionPoints, substitutionOpinion),
    flexibilityGeneralOpinion = op(flexibilityGeneralPoints, flexibilityGeneralOpinion),
    observationCapacityOpinion = op(observationCapacityPoints, observationCapacityOpinion),
    recuperationCapacityOpinion = op(recuperationCapacityPoints, recuperationCapacityOpinion),
    responseCapacityOpinion = op(responseCapacityPoints, responseCapacityOpinion),
    taskAdaptationOpinion = op(taskAdaptationPoints, taskAdaptationOpinion),
    robustnessGeneralOpinion = op(robustnessGeneralPoints, robustnessGeneralOpinion),
    usabilityGeneralOpinion = op(usabilityGeneralPoints, usabilityGeneralOpinion),
    equitableUseOpinion = op(equitableUsePoints, equitableUseOpinion),
    flexibilityUseOpinion = op(flexibilityUsePoints, flexibilityUseOpinion),
    simpleAndIntuitiveUseOpinion = op(simpleAndIntuitiveUsePoints, simpleAndIntuitiveUseOpinion),
    perceptibleInformationOpinion = op(perceptibleInformationPoints, perceptibleInformationOpinion),
    toleranceErrorOpinion = op(toleranceErrorPoints, toleranceErrorOpinion),
    lowPhysicalEffortOpinion = op(lowPhysicalEffortPoints, lowPhysicalEffortOpinion),
    sizeAndSpaceOpinion = op(sizeAndSpacePoints, sizeAndSpaceOpinion),
    visualProtanopiaOpinion = op(visualProtanopiaPoints, visualProtanopiaOpinion),
    visualDeuteranopiaOpinion = op(visualDeuteranopiaPoints, visualDeuteranopiaOpinion),
    visualTritanopiaOpinion = op(visualTritanopiaPoints, visualTritanopiaOpinion),
    reducedVisionZoomAdapterOpinion = op(reducedVisionZoomAdapterPoints, reducedVisionZoomAdapterOpinion),
    blindnessScreenReaderOpinion = op(blindnessScreenReaderPoints, blindnessScreenReaderOpinion),
    blindnessElementsSoundOpinion = op(blindnessElementsSoundPoints, blindnessElementsSoundOpinion),
    textInformationOpinion = op(textInformationPoints, textInformationOpinion),
    simpleTextOpinion = op(simpleTextPoints, simpleTextOpinion),
    reducedMobilityOpinion = op(reducedMobilityPoints, reducedMobilityOpinion),
    cognitiveSimpleOpinion = op(cognitiveSimplePoints, cognitiveSimpleOpinion),
    colorSchemeDarkOpinion = op(colorSchemeDarkPoints, colorSchemeDarkOpinion),
    colorSchemeLightOpinion = op(colorSchemeLightPoints, colorSchemeLightOpinion),
    colorSchemeContrastOpinion = op(colorSchemeContrastPoints, colorSchemeContrastOpinion),
    colorSchemeGeneralOpinion = op(colorSchemeGeneralPoints, colorSchemeGeneralOpinion),
    fontTypeTitleOpinion = op(fontTypeTitlePoints, fontTypeTitleOpinion),
    fontTypeBodyOpinion = op(fontTypeBodyPoints, fontTypeBodyOpinion),
    fontTypeSpecialOpinion = op(fontTypeSpecialPoints, fontTypeSpecialOpinion),
    fontTypeGeneralOpinion = op(fontTypeGeneralPoints, fontTypeGeneralOpinion),
    windowAdaptationOpinion = op(windowAdaptationPoints, windowAdaptationOpinion),
    navigationButtonOpinion = op(navigationButtonPoints, navigationButtonOpinion),
    navigationBottomBarOpinion = op(navigationBottomBarPoints, navigationBottomBarOpinion),
    navigationGeneralOpinion = op(navigationGeneralPoints, navigationGeneralOpinion),
    splashScreenDesignOpinion = op(splashScreenDesignPoints, splashScreenDesignOpinion),
    splashScreenGeneralOpinion = op(splashScreenGeneralPoints, splashScreenGeneralOpinion),
    guideScreenDesignOpinion = op(guideScreenDesignPoints, guideScreenDesignOpinion),
    guideScreenContentOpinion = op(guideScreenContentPoints, guideScreenContentOpinion),
    guideScreenGeneralOpinion = op(guideScreenGeneralPoints, guideScreenGeneralOpinion),
    menuScreenDesignOpinion = op(menuScreenDesignPoints, menuScreenDesignOpinion),
    menuScreenContentOpinion = op(menuScreenContentPoints, menuScreenContentOpinion),
    menuScreenGeneralOpinion = op(menuScreenGeneralPoints, menuScreenGeneralOpinion),
    loginScreenDesignOpinion = op(loginScreenDesignPoints, loginScreenDesignOpinion),
    loginScreenContentOpinion = op(loginScreenContentPoints, loginScreenContentOpinion),
    loginScreenGeneralOpinion = op(loginScreenGeneralPoints, loginScreenGeneralOpinion),
    signScreenDesignOpinion = op(signScreenDesignPoints, signScreenDesignOpinion),
    signScreenContentOpinion = op(signScreenContentPoints, signScreenContentOpinion),
    signScreenGeneralOpinion = op(signScreenGeneralPoints, signScreenGeneralOpinion),
    homeScreenDesignOpinion = op(homeScreenDesignPoints, homeScreenDesignOpinion),
    homeScreenContentOpinion = op(homeScreenContentPoints, homeScreenContentOpinion),
    homeScreenGeneralOpinion = op(homeScreenGeneralPoints, homeScreenGeneralOpinion),
    settingsScreenDesignOpinion = op(settingsScreenDesignPoints, settingsScreenDesignOpinion),
    settingsScreenContentOpinion = op(settingsScreenContentPoints, settingsScreenContentOpinion),
    settingsScreenGeneralOpinion = op(settingsScreenGeneralPoints, settingsScreenGeneralOpinion),
    profileScreenDesignOpinion = op(profileScreenDesignPoints, profileScreenDesignOpinion),
    profileScreenContentOpinion = op(profileScreenContentPoints, profileScreenContentOpinion),
    profileScreenGeneralOpinion = op(profileScreenGeneralPoints, profileScreenGeneralOpinion),
    chatScreenDesignOpinion = op(chatScreenDesignPoints, chatScreenDesignOpinion),
    chatScreenContentOpinion = op(chatScreenContentPoints, chatScreenContentOpinion),
    chatScreenGeneralOpinion = op(chatScreenGeneralPoints, chatScreenGeneralOpinion),
    groupScreenDesignOpinion = op(groupScreenDesignPoints, groupScreenDesignOpinion),
    groupScreenContentOpinion = op(groupScreenContentPoints, groupScreenContentOpinion),
    groupScreenGeneralOpinion = op(groupScreenGeneralPoints, groupScreenGeneralOpinion),
    playScreenDesignOpinion = op(playScreenDesignPoints, playScreenDesignOpinion),
    playScreenContentOpinion = op(playScreenContentPoints, playScreenContentOpinion),
    playScreenGeneralOpinion = op(playScreenGeneralPoints, playScreenGeneralOpinion),
    mysteryNumberScreenDesignOpinion = op(mysteryNumberScreenDesignPoints, mysteryNumberScreenDesignOpinion),
    mysteryNumberScreenContentOpinion = op(mysteryNumberScreenContentPoints, mysteryNumberScreenContentOpinion),
    mysteryNumberScreenGeneralOpinion = op(mysteryNumberScreenGeneralPoints, mysteryNumberScreenGeneralOpinion),
    wordPassScreenDesignOpinion = op(wordPassScreenDesignPoints, wordPassScreenDesignOpinion),
    wordPassScreenContentOpinion = op(wordPassScreenContentPoints, wordPassScreenContentOpinion),
    wordPassScreenGeneralOpinion = op(wordPassScreenGeneralPoints, wordPassScreenGeneralOpinion),
    quizScreenDesignOpinion = op(quizScreenDesignPoints, quizScreenDesignOpinion),
    quizScreenContentOpinion = op(quizScreenContentPoints, quizScreenContentOpinion),
    quizScreenGeneralOpinion = op(quizScreenGeneralPoints, quizScreenGeneralOpinion),
    familiesScreenDesignOpinion = op(familiesScreenDesignPoints, familiesScreenDesignOpinion),
    familiesScreenContentOpinion = op(familiesScreenContentPoints, familiesScreenContentOpinion),
    familiesScreenGeneralOpinion = op(familiesScreenGeneralPoints, familiesScreenGeneralOpinion),
    surveyScreenDesignOpinion = op(surveyScreenDesignPoints, surveyScreenDesignOpinion),
    surveyScreenContentOpinion = op(surveyScreenContentPoints, surveyScreenContentOpinion),
    surveyScreenGeneralOpinion = op(surveyScreenGeneralPoints, surveyScreenGeneralOpinion),
)

fun SurveyEntity.toSurveyModel() = SurveyModel(
    authorFirebaseId = authorFirebaseId,
    authorNickName = authorNickName,
    authorAge = authorAge,
    profession = profession,
    language = Languages.entries[language],
    androidKnowing = androidKnowing,
    applicationsKnowing = applicationsKnowing,
    gamesKnowing = gamesKnowing,
    socialNetworksKnowing = socialNetworksKnowing,
    otherKnowing = otherKnowing,
    predictionOpinion = op(predictionPoints, predictionOpinion),
    synthesisOpinion = op(synthesisPoints, synthesisOpinion),
    familiarityOpinion = op(familiarityPoints, familiarityOpinion),
    generalityOpinion = op(generalityPoints, generalityOpinion),
    consistencyOpinion = op(consistencyPoints, consistencyOpinion),
    learnabilityGeneralOpinion = op(learnabilityGeneralPoints, learnabilityGeneralOpinion),
    dialogInitiativeOpinion = op(dialogInitiativePoints, dialogInitiativeOpinion),
    multitaskingOpinion = op(multitaskingPoints, multitaskingOpinion),
    taskControlOpinion = op(taskControlPoints, taskControlOpinion),
    adaptationOpinion = op(adaptationPoints, adaptationOpinion),
    substitutionOpinion = op(substitutionPoints, substitutionOpinion),
    flexibilityGeneralOpinion = op(flexibilityGeneralPoints, flexibilityGeneralOpinion),
    observationCapacityOpinion = op(observationCapacityPoints, observationCapacityOpinion),
    recuperationCapacityOpinion = op(recuperationCapacityPoints, recuperationCapacityOpinion),
    responseCapacityOpinion = op(responseCapacityPoints, responseCapacityOpinion),
    taskAdaptationOpinion = op(taskAdaptationPoints, taskAdaptationOpinion),
    robustnessGeneralOpinion = op(robustnessGeneralPoints, robustnessGeneralOpinion),
    usabilityGeneralOpinion = op(usabilityGeneralPoints, usabilityGeneralOpinion),
    equitableUseOpinion = op(equitableUsePoints, equitableUseOpinion),
    flexibilityUseOpinion = op(flexibilityUsePoints, flexibilityUseOpinion),
    simpleAndIntuitiveUseOpinion = op(simpleAndIntuitiveUsePoints, simpleAndIntuitiveUseOpinion),
    perceptibleInformationOpinion = op(perceptibleInformationPoints, perceptibleInformationOpinion),
    toleranceErrorOpinion = op(toleranceErrorPoints, toleranceErrorOpinion),
    lowPhysicalEffortOpinion = op(lowPhysicalEffortPoints, lowPhysicalEffortOpinion),
    sizeAndSpaceOpinion = op(sizeAndSpacePoints, sizeAndSpaceOpinion),
    visualProtanopiaOpinion = op(visualProtanopiaPoints, visualProtanopiaOpinion),
    visualDeuteranopiaOpinion = op(visualDeuteranopiaPoints, visualDeuteranopiaOpinion),
    visualTritanopiaOpinion = op(visualTritanopiaPoints, visualTritanopiaOpinion),
    reducedVisionZoomAdapterOpinion = op(reducedVisionZoomAdapterPoints, reducedVisionZoomAdapterOpinion),
    blindnessScreenReaderOpinion = op(blindnessScreenReaderPoints, blindnessScreenReaderOpinion),
    blindnessElementsSoundOpinion = op(blindnessElementsSoundPoints, blindnessElementsSoundOpinion),
    textInformationOpinion = op(textInformationPoints, textInformationOpinion),
    simpleTextOpinion = op(simpleTextPoints, simpleTextOpinion),
    reducedMobilityOpinion = op(reducedMobilityPoints, reducedMobilityOpinion),
    cognitiveSimpleOpinion = op(cognitiveSimplePoints, cognitiveSimpleOpinion),
    colorSchemeDarkOpinion = op(colorSchemeDarkPoints, colorSchemeDarkOpinion),
    colorSchemeLightOpinion = op(colorSchemeLightPoints, colorSchemeLightOpinion),
    colorSchemeContrastOpinion = op(colorSchemeContrastPoints, colorSchemeContrastOpinion),
    colorSchemeGeneralOpinion = op(colorSchemeGeneralPoints, colorSchemeGeneralOpinion),
    fontTypeTitleOpinion = op(fontTypeTitlePoints, fontTypeTitleOpinion),
    fontTypeBodyOpinion = op(fontTypeBodyPoints, fontTypeBodyOpinion),
    fontTypeSpecialOpinion = op(fontTypeSpecialPoints, fontTypeSpecialOpinion),
    fontTypeGeneralOpinion = op(fontTypeGeneralPoints, fontTypeGeneralOpinion),
    windowAdaptationOpinion = op(windowAdaptationPoints, windowAdaptationOpinion),
    navigationButtonOpinion = op(navigationButtonPoints, navigationButtonOpinion),
    navigationBottomBarOpinion = op(navigationBottomBarPoints, navigationBottomBarOpinion),
    navigationGeneralOpinion = op(navigationGeneralPoints, navigationGeneralOpinion),
    splashScreenDesignOpinion = op(splashScreenDesignPoints, splashScreenDesignOpinion),
    splashScreenGeneralOpinion = op(splashScreenGeneralPoints, splashScreenGeneralOpinion),
    guideScreenDesignOpinion = op(guideScreenDesignPoints, guideScreenDesignOpinion),
    guideScreenContentOpinion = op(guideScreenContentPoints, guideScreenContentOpinion),
    guideScreenGeneralOpinion = op(guideScreenGeneralPoints, guideScreenGeneralOpinion),
    menuScreenDesignOpinion = op(menuScreenDesignPoints, menuScreenDesignOpinion),
    menuScreenContentOpinion = op(menuScreenContentPoints, menuScreenContentOpinion),
    menuScreenGeneralOpinion = op(menuScreenGeneralPoints, menuScreenGeneralOpinion),
    loginScreenDesignOpinion = op(loginScreenDesignPoints, loginScreenDesignOpinion),
    loginScreenContentOpinion = op(loginScreenContentPoints, loginScreenContentOpinion),
    loginScreenGeneralOpinion = op(loginScreenGeneralPoints, loginScreenGeneralOpinion),
    signScreenDesignOpinion = op(signScreenDesignPoints, signScreenDesignOpinion),
    signScreenContentOpinion = op(signScreenContentPoints, signScreenContentOpinion),
    signScreenGeneralOpinion = op(signScreenGeneralPoints, signScreenGeneralOpinion),
    homeScreenDesignOpinion = op(homeScreenDesignPoints, homeScreenDesignOpinion),
    homeScreenContentOpinion = op(homeScreenContentPoints, homeScreenContentOpinion),
    homeScreenGeneralOpinion = op(homeScreenGeneralPoints, homeScreenGeneralOpinion),
    settingsScreenDesignOpinion = op(settingsScreenDesignPoints, settingsScreenDesignOpinion),
    settingsScreenContentOpinion = op(settingsScreenContentPoints, settingsScreenContentOpinion),
    settingsScreenGeneralOpinion = op(settingsScreenGeneralPoints, settingsScreenGeneralOpinion),
    profileScreenDesignOpinion = op(profileScreenDesignPoints, profileScreenDesignOpinion),
    profileScreenContentOpinion = op(profileScreenContentPoints, profileScreenContentOpinion),
    profileScreenGeneralOpinion = op(profileScreenGeneralPoints, profileScreenGeneralOpinion),
    chatScreenDesignOpinion = op(chatScreenDesignPoints, chatScreenDesignOpinion),
    chatScreenContentOpinion = op(chatScreenContentPoints, chatScreenContentOpinion),
    chatScreenGeneralOpinion = op(chatScreenGeneralPoints, chatScreenGeneralOpinion),
    groupScreenDesignOpinion = op(groupScreenDesignPoints, groupScreenDesignOpinion),
    groupScreenContentOpinion = op(groupScreenContentPoints, groupScreenContentOpinion),
    groupScreenGeneralOpinion = op(groupScreenGeneralPoints, groupScreenGeneralOpinion),
    playScreenDesignOpinion = op(playScreenDesignPoints, playScreenDesignOpinion),
    playScreenContentOpinion = op(playScreenContentPoints, playScreenContentOpinion),
    playScreenGeneralOpinion = op(playScreenGeneralPoints, playScreenGeneralOpinion),
    mysteryNumberScreenDesignOpinion = op(mysteryNumberScreenDesignPoints, mysteryNumberScreenDesignOpinion),
    mysteryNumberScreenContentOpinion = op(mysteryNumberScreenContentPoints, mysteryNumberScreenContentOpinion),
    mysteryNumberScreenGeneralOpinion = op(mysteryNumberScreenGeneralPoints, mysteryNumberScreenGeneralOpinion),
    wordPassScreenDesignOpinion = op(wordPassScreenDesignPoints, wordPassScreenDesignOpinion),
    wordPassScreenContentOpinion = op(wordPassScreenContentPoints, wordPassScreenContentOpinion),
    wordPassScreenGeneralOpinion = op(wordPassScreenGeneralPoints, wordPassScreenGeneralOpinion),
    quizScreenDesignOpinion = op(quizScreenDesignPoints, quizScreenDesignOpinion),
    quizScreenContentOpinion = op(quizScreenContentPoints, quizScreenContentOpinion),
    quizScreenGeneralOpinion = op(quizScreenGeneralPoints, quizScreenGeneralOpinion),
    familiesScreenDesignOpinion = op(familiesScreenDesignPoints, familiesScreenDesignOpinion),
    familiesScreenContentOpinion = op(familiesScreenContentPoints, familiesScreenContentOpinion),
    familiesScreenGeneralOpinion = op(familiesScreenGeneralPoints, familiesScreenGeneralOpinion),
    surveyScreenDesignOpinion = op(surveyScreenDesignPoints, surveyScreenDesignOpinion),
    surveyScreenContentOpinion = op(surveyScreenContentPoints, surveyScreenContentOpinion),
    surveyScreenGeneralOpinion = op(surveyScreenGeneralPoints, surveyScreenGeneralOpinion),
)

fun SurveyModel.toSurveyDocument() = SurveyDocument(
    authorFirebaseId = authorFirebaseId,
    authorNickName = authorNickName,
    authorAge = authorAge,
    profession = profession,
    language = language.ordinal,
    androidKnowing = androidKnowing,
    applicationsKnowing = applicationsKnowing,
    gamesKnowing = gamesKnowing,
    socialNetworksKnowing = socialNetworksKnowing,
    otherKnowing = otherKnowing,
    predictionPoints = predictionOpinion.points, predictionOpinion = predictionOpinion.opinion,
    synthesisPoints = synthesisOpinion.points, synthesisOpinion = synthesisOpinion.opinion,
    familiarityPoints = familiarityOpinion.points, familiarityOpinion = familiarityOpinion.opinion,
    generalityPoints = generalityOpinion.points, generalityOpinion = generalityOpinion.opinion,
    consistencyPoints = consistencyOpinion.points, consistencyOpinion = consistencyOpinion.opinion,
    learnabilityGeneralPoints = learnabilityGeneralOpinion.points, learnabilityGeneralOpinion = learnabilityGeneralOpinion.opinion,
    dialogInitiativePoints = dialogInitiativeOpinion.points, dialogInitiativeOpinion = dialogInitiativeOpinion.opinion,
    multitaskingPoints = multitaskingOpinion.points, multitaskingOpinion = multitaskingOpinion.opinion,
    taskControlPoints = taskControlOpinion.points, taskControlOpinion = taskControlOpinion.opinion,
    adaptationPoints = adaptationOpinion.points, adaptationOpinion = adaptationOpinion.opinion,
    substitutionPoints = substitutionOpinion.points, substitutionOpinion = substitutionOpinion.opinion,
    flexibilityGeneralPoints = flexibilityGeneralOpinion.points, flexibilityGeneralOpinion = flexibilityGeneralOpinion.opinion,
    observationCapacityPoints = observationCapacityOpinion.points, observationCapacityOpinion = observationCapacityOpinion.opinion,
    recuperationCapacityPoints = recuperationCapacityOpinion.points, recuperationCapacityOpinion = recuperationCapacityOpinion.opinion,
    responseCapacityPoints = responseCapacityOpinion.points, responseCapacityOpinion = responseCapacityOpinion.opinion,
    taskAdaptationPoints = taskAdaptationOpinion.points, taskAdaptationOpinion = taskAdaptationOpinion.opinion,
    robustnessGeneralPoints = robustnessGeneralOpinion.points, robustnessGeneralOpinion = robustnessGeneralOpinion.opinion,
    usabilityGeneralPoints = usabilityGeneralOpinion.points, usabilityGeneralOpinion = usabilityGeneralOpinion.opinion,
    equitableUsePoints = equitableUseOpinion.points, equitableUseOpinion = equitableUseOpinion.opinion,
    flexibilityUsePoints = flexibilityUseOpinion.points, flexibilityUseOpinion = flexibilityUseOpinion.opinion,
    simpleAndIntuitiveUsePoints = simpleAndIntuitiveUseOpinion.points, simpleAndIntuitiveUseOpinion = simpleAndIntuitiveUseOpinion.opinion,
    perceptibleInformationPoints = perceptibleInformationOpinion.points, perceptibleInformationOpinion = perceptibleInformationOpinion.opinion,
    toleranceErrorPoints = toleranceErrorOpinion.points, toleranceErrorOpinion = toleranceErrorOpinion.opinion,
    lowPhysicalEffortPoints = lowPhysicalEffortOpinion.points, lowPhysicalEffortOpinion = lowPhysicalEffortOpinion.opinion,
    sizeAndSpacePoints = sizeAndSpaceOpinion.points, sizeAndSpaceOpinion = sizeAndSpaceOpinion.opinion,
    visualProtanopiaPoints = visualProtanopiaOpinion.points, visualProtanopiaOpinion = visualProtanopiaOpinion.opinion,
    visualDeuteranopiaPoints = visualDeuteranopiaOpinion.points, visualDeuteranopiaOpinion = visualDeuteranopiaOpinion.opinion,
    visualTritanopiaPoints = visualTritanopiaOpinion.points, visualTritanopiaOpinion = visualTritanopiaOpinion.opinion,
    reducedVisionZoomAdapterPoints = reducedVisionZoomAdapterOpinion.points, reducedVisionZoomAdapterOpinion = reducedVisionZoomAdapterOpinion.opinion,
    blindnessScreenReaderPoints = blindnessScreenReaderOpinion.points, blindnessScreenReaderOpinion = blindnessScreenReaderOpinion.opinion,
    blindnessElementsSoundPoints = blindnessElementsSoundOpinion.points, blindnessElementsSoundOpinion = blindnessElementsSoundOpinion.opinion,
    textInformationPoints = textInformationOpinion.points, textInformationOpinion = textInformationOpinion.opinion,
    simpleTextPoints = simpleTextOpinion.points, simpleTextOpinion = simpleTextOpinion.opinion,
    reducedMobilityPoints = reducedMobilityOpinion.points, reducedMobilityOpinion = reducedMobilityOpinion.opinion,
    cognitiveSimplePoints = cognitiveSimpleOpinion.points, cognitiveSimpleOpinion = cognitiveSimpleOpinion.opinion,
    colorSchemeDarkPoints = colorSchemeDarkOpinion.points, colorSchemeDarkOpinion = colorSchemeDarkOpinion.opinion,
    colorSchemeLightPoints = colorSchemeLightOpinion.points, colorSchemeLightOpinion = colorSchemeLightOpinion.opinion,
    colorSchemeContrastPoints = colorSchemeContrastOpinion.points, colorSchemeContrastOpinion = colorSchemeContrastOpinion.opinion,
    colorSchemeGeneralPoints = colorSchemeGeneralOpinion.points, colorSchemeGeneralOpinion = colorSchemeGeneralOpinion.opinion,
    fontTypeTitlePoints = fontTypeTitleOpinion.points, fontTypeTitleOpinion = fontTypeTitleOpinion.opinion,
    fontTypeBodyPoints = fontTypeBodyOpinion.points, fontTypeBodyOpinion = fontTypeBodyOpinion.opinion,
    fontTypeSpecialPoints = fontTypeSpecialOpinion.points, fontTypeSpecialOpinion = fontTypeSpecialOpinion.opinion,
    fontTypeGeneralPoints = fontTypeGeneralOpinion.points, fontTypeGeneralOpinion = fontTypeGeneralOpinion.opinion,
    windowAdaptationPoints = windowAdaptationOpinion.points, windowAdaptationOpinion = windowAdaptationOpinion.opinion,
    navigationButtonPoints = navigationButtonOpinion.points, navigationButtonOpinion = navigationButtonOpinion.opinion,
    navigationBottomBarPoints = navigationBottomBarOpinion.points, navigationBottomBarOpinion = navigationBottomBarOpinion.opinion,
    navigationGeneralPoints = navigationGeneralOpinion.points, navigationGeneralOpinion = navigationGeneralOpinion.opinion,
    splashScreenDesignPoints = splashScreenDesignOpinion.points, splashScreenDesignOpinion = splashScreenDesignOpinion.opinion,
    splashScreenGeneralPoints = splashScreenGeneralOpinion.points, splashScreenGeneralOpinion = splashScreenGeneralOpinion.opinion,
    guideScreenDesignPoints = guideScreenDesignOpinion.points, guideScreenDesignOpinion = guideScreenDesignOpinion.opinion,
    guideScreenContentPoints = guideScreenContentOpinion.points, guideScreenContentOpinion = guideScreenContentOpinion.opinion,
    guideScreenGeneralPoints = guideScreenGeneralOpinion.points, guideScreenGeneralOpinion = guideScreenGeneralOpinion.opinion,
    menuScreenDesignPoints = menuScreenDesignOpinion.points, menuScreenDesignOpinion = menuScreenDesignOpinion.opinion,
    menuScreenContentPoints = menuScreenContentOpinion.points, menuScreenContentOpinion = menuScreenContentOpinion.opinion,
    menuScreenGeneralPoints = menuScreenGeneralOpinion.points, menuScreenGeneralOpinion = menuScreenGeneralOpinion.opinion,
    loginScreenDesignPoints = loginScreenDesignOpinion.points, loginScreenDesignOpinion = loginScreenDesignOpinion.opinion,
    loginScreenContentPoints = loginScreenContentOpinion.points, loginScreenContentOpinion = loginScreenContentOpinion.opinion,
    loginScreenGeneralPoints = loginScreenGeneralOpinion.points, loginScreenGeneralOpinion = loginScreenGeneralOpinion.opinion,
    signScreenDesignPoints = signScreenDesignOpinion.points, signScreenDesignOpinion = signScreenDesignOpinion.opinion,
    signScreenContentPoints = signScreenContentOpinion.points, signScreenContentOpinion = signScreenContentOpinion.opinion,
    signScreenGeneralPoints = signScreenGeneralOpinion.points, signScreenGeneralOpinion = signScreenGeneralOpinion.opinion,
    homeScreenDesignPoints = homeScreenDesignOpinion.points, homeScreenDesignOpinion = homeScreenDesignOpinion.opinion,
    homeScreenContentPoints = homeScreenContentOpinion.points, homeScreenContentOpinion = homeScreenContentOpinion.opinion,
    homeScreenGeneralPoints = homeScreenGeneralOpinion.points, homeScreenGeneralOpinion = homeScreenGeneralOpinion.opinion,
    settingsScreenDesignPoints = settingsScreenDesignOpinion.points, settingsScreenDesignOpinion = settingsScreenDesignOpinion.opinion,
    settingsScreenContentPoints = settingsScreenContentOpinion.points, settingsScreenContentOpinion = settingsScreenContentOpinion.opinion,
    settingsScreenGeneralPoints = settingsScreenGeneralOpinion.points, settingsScreenGeneralOpinion = settingsScreenGeneralOpinion.opinion,
    profileScreenDesignPoints = profileScreenDesignOpinion.points, profileScreenDesignOpinion = profileScreenDesignOpinion.opinion,
    profileScreenContentPoints = profileScreenContentOpinion.points, profileScreenContentOpinion = profileScreenContentOpinion.opinion,
    profileScreenGeneralPoints = profileScreenGeneralOpinion.points, profileScreenGeneralOpinion = profileScreenGeneralOpinion.opinion,
    chatScreenDesignPoints = chatScreenDesignOpinion.points, chatScreenDesignOpinion = chatScreenDesignOpinion.opinion,
    chatScreenContentPoints = chatScreenContentOpinion.points, chatScreenContentOpinion = chatScreenContentOpinion.opinion,
    chatScreenGeneralPoints = chatScreenGeneralOpinion.points, chatScreenGeneralOpinion = chatScreenGeneralOpinion.opinion,
    groupScreenDesignPoints = groupScreenDesignOpinion.points, groupScreenDesignOpinion = groupScreenDesignOpinion.opinion,
    groupScreenContentPoints = groupScreenContentOpinion.points, groupScreenContentOpinion = groupScreenContentOpinion.opinion,
    groupScreenGeneralPoints = groupScreenGeneralOpinion.points, groupScreenGeneralOpinion = groupScreenGeneralOpinion.opinion,
    playScreenDesignPoints = playScreenDesignOpinion.points, playScreenDesignOpinion = playScreenDesignOpinion.opinion,
    playScreenContentPoints = playScreenContentOpinion.points, playScreenContentOpinion = playScreenContentOpinion.opinion,
    playScreenGeneralPoints = playScreenGeneralOpinion.points, playScreenGeneralOpinion = playScreenGeneralOpinion.opinion,
    mysteryNumberScreenDesignPoints = mysteryNumberScreenDesignOpinion.points, mysteryNumberScreenDesignOpinion = mysteryNumberScreenDesignOpinion.opinion,
    mysteryNumberScreenContentPoints = mysteryNumberScreenContentOpinion.points, mysteryNumberScreenContentOpinion = mysteryNumberScreenContentOpinion.opinion,
    mysteryNumberScreenGeneralPoints = mysteryNumberScreenGeneralOpinion.points, mysteryNumberScreenGeneralOpinion = mysteryNumberScreenGeneralOpinion.opinion,
    wordPassScreenDesignPoints = wordPassScreenDesignOpinion.points, wordPassScreenDesignOpinion = wordPassScreenDesignOpinion.opinion,
    wordPassScreenContentPoints = wordPassScreenContentOpinion.points, wordPassScreenContentOpinion = wordPassScreenContentOpinion.opinion,
    wordPassScreenGeneralPoints = wordPassScreenGeneralOpinion.points, wordPassScreenGeneralOpinion = wordPassScreenGeneralOpinion.opinion,
    quizScreenDesignPoints = quizScreenDesignOpinion.points, quizScreenDesignOpinion = quizScreenDesignOpinion.opinion,
    quizScreenContentPoints = quizScreenContentOpinion.points, quizScreenContentOpinion = quizScreenContentOpinion.opinion,
    quizScreenGeneralPoints = quizScreenGeneralOpinion.points, quizScreenGeneralOpinion = quizScreenGeneralOpinion.opinion,
    familiesScreenDesignPoints = familiesScreenDesignOpinion.points, familiesScreenDesignOpinion = familiesScreenDesignOpinion.opinion,
    familiesScreenContentPoints = familiesScreenContentOpinion.points, familiesScreenContentOpinion = familiesScreenContentOpinion.opinion,
    familiesScreenGeneralPoints = familiesScreenGeneralOpinion.points, familiesScreenGeneralOpinion = familiesScreenGeneralOpinion.opinion,
    surveyScreenDesignPoints = surveyScreenDesignOpinion.points, surveyScreenDesignOpinion = surveyScreenDesignOpinion.opinion,
    surveyScreenContentPoints = surveyScreenContentOpinion.points, surveyScreenContentOpinion = surveyScreenContentOpinion.opinion,
    surveyScreenGeneralPoints = surveyScreenGeneralOpinion.points, surveyScreenGeneralOpinion = surveyScreenGeneralOpinion.opinion,
)

fun SurveyModel.toSurveyEntity() = SurveyEntity(
    authorFirebaseId = authorFirebaseId,
    authorNickName = authorNickName,
    authorAge = authorAge,
    profession = profession,
    language = language.ordinal,
    androidKnowing = androidKnowing,
    applicationsKnowing = applicationsKnowing,
    gamesKnowing = gamesKnowing,
    socialNetworksKnowing = socialNetworksKnowing,
    otherKnowing = otherKnowing,
    predictionPoints = predictionOpinion.points, predictionOpinion = predictionOpinion.opinion,
    synthesisPoints = synthesisOpinion.points, synthesisOpinion = synthesisOpinion.opinion,
    familiarityPoints = familiarityOpinion.points, familiarityOpinion = familiarityOpinion.opinion,
    generalityPoints = generalityOpinion.points, generalityOpinion = generalityOpinion.opinion,
    consistencyPoints = consistencyOpinion.points, consistencyOpinion = consistencyOpinion.opinion,
    learnabilityGeneralPoints = learnabilityGeneralOpinion.points, learnabilityGeneralOpinion = learnabilityGeneralOpinion.opinion,
    dialogInitiativePoints = dialogInitiativeOpinion.points, dialogInitiativeOpinion = dialogInitiativeOpinion.opinion,
    multitaskingPoints = multitaskingOpinion.points, multitaskingOpinion = multitaskingOpinion.opinion,
    taskControlPoints = taskControlOpinion.points, taskControlOpinion = taskControlOpinion.opinion,
    adaptationPoints = adaptationOpinion.points, adaptationOpinion = adaptationOpinion.opinion,
    substitutionPoints = substitutionOpinion.points, substitutionOpinion = substitutionOpinion.opinion,
    flexibilityGeneralPoints = flexibilityGeneralOpinion.points, flexibilityGeneralOpinion = flexibilityGeneralOpinion.opinion,
    observationCapacityPoints = observationCapacityOpinion.points, observationCapacityOpinion = observationCapacityOpinion.opinion,
    recuperationCapacityPoints = recuperationCapacityOpinion.points, recuperationCapacityOpinion = recuperationCapacityOpinion.opinion,
    responseCapacityPoints = responseCapacityOpinion.points, responseCapacityOpinion = responseCapacityOpinion.opinion,
    taskAdaptationPoints = taskAdaptationOpinion.points, taskAdaptationOpinion = taskAdaptationOpinion.opinion,
    robustnessGeneralPoints = robustnessGeneralOpinion.points, robustnessGeneralOpinion = robustnessGeneralOpinion.opinion,
    usabilityGeneralPoints = usabilityGeneralOpinion.points, usabilityGeneralOpinion = usabilityGeneralOpinion.opinion,
    equitableUsePoints = equitableUseOpinion.points, equitableUseOpinion = equitableUseOpinion.opinion,
    flexibilityUsePoints = flexibilityUseOpinion.points, flexibilityUseOpinion = flexibilityUseOpinion.opinion,
    simpleAndIntuitiveUsePoints = simpleAndIntuitiveUseOpinion.points, simpleAndIntuitiveUseOpinion = simpleAndIntuitiveUseOpinion.opinion,
    perceptibleInformationPoints = perceptibleInformationOpinion.points, perceptibleInformationOpinion = perceptibleInformationOpinion.opinion,
    toleranceErrorPoints = toleranceErrorOpinion.points, toleranceErrorOpinion = toleranceErrorOpinion.opinion,
    lowPhysicalEffortPoints = lowPhysicalEffortOpinion.points, lowPhysicalEffortOpinion = lowPhysicalEffortOpinion.opinion,
    sizeAndSpacePoints = sizeAndSpaceOpinion.points, sizeAndSpaceOpinion = sizeAndSpaceOpinion.opinion,
    visualProtanopiaPoints = visualProtanopiaOpinion.points, visualProtanopiaOpinion = visualProtanopiaOpinion.opinion,
    visualDeuteranopiaPoints = visualDeuteranopiaOpinion.points, visualDeuteranopiaOpinion = visualDeuteranopiaOpinion.opinion,
    visualTritanopiaPoints = visualTritanopiaOpinion.points, visualTritanopiaOpinion = visualTritanopiaOpinion.opinion,
    reducedVisionZoomAdapterPoints = reducedVisionZoomAdapterOpinion.points, reducedVisionZoomAdapterOpinion = reducedVisionZoomAdapterOpinion.opinion,
    blindnessScreenReaderPoints = blindnessScreenReaderOpinion.points, blindnessScreenReaderOpinion = blindnessScreenReaderOpinion.opinion,
    blindnessElementsSoundPoints = blindnessElementsSoundOpinion.points, blindnessElementsSoundOpinion = blindnessElementsSoundOpinion.opinion,
    textInformationPoints = textInformationOpinion.points, textInformationOpinion = textInformationOpinion.opinion,
    simpleTextPoints = simpleTextOpinion.points, simpleTextOpinion = simpleTextOpinion.opinion,
    reducedMobilityPoints = reducedMobilityOpinion.points, reducedMobilityOpinion = reducedMobilityOpinion.opinion,
    cognitiveSimplePoints = cognitiveSimpleOpinion.points, cognitiveSimpleOpinion = cognitiveSimpleOpinion.opinion,
    colorSchemeDarkPoints = colorSchemeDarkOpinion.points, colorSchemeDarkOpinion = colorSchemeDarkOpinion.opinion,
    colorSchemeLightPoints = colorSchemeLightOpinion.points, colorSchemeLightOpinion = colorSchemeLightOpinion.opinion,
    colorSchemeContrastPoints = colorSchemeContrastOpinion.points, colorSchemeContrastOpinion = colorSchemeContrastOpinion.opinion,
    colorSchemeGeneralPoints = colorSchemeGeneralOpinion.points, colorSchemeGeneralOpinion = colorSchemeGeneralOpinion.opinion,
    fontTypeTitlePoints = fontTypeTitleOpinion.points, fontTypeTitleOpinion = fontTypeTitleOpinion.opinion,
    fontTypeBodyPoints = fontTypeBodyOpinion.points, fontTypeBodyOpinion = fontTypeBodyOpinion.opinion,
    fontTypeSpecialPoints = fontTypeSpecialOpinion.points, fontTypeSpecialOpinion = fontTypeSpecialOpinion.opinion,
    fontTypeGeneralPoints = fontTypeGeneralOpinion.points, fontTypeGeneralOpinion = fontTypeGeneralOpinion.opinion,
    windowAdaptationPoints = windowAdaptationOpinion.points, windowAdaptationOpinion = windowAdaptationOpinion.opinion,
    navigationButtonPoints = navigationButtonOpinion.points, navigationButtonOpinion = navigationButtonOpinion.opinion,
    navigationBottomBarPoints = navigationBottomBarOpinion.points, navigationBottomBarOpinion = navigationBottomBarOpinion.opinion,
    navigationGeneralPoints = navigationGeneralOpinion.points, navigationGeneralOpinion = navigationGeneralOpinion.opinion,
    splashScreenDesignPoints = splashScreenDesignOpinion.points, splashScreenDesignOpinion = splashScreenDesignOpinion.opinion,
    splashScreenGeneralPoints = splashScreenGeneralOpinion.points, splashScreenGeneralOpinion = splashScreenGeneralOpinion.opinion,
    guideScreenDesignPoints = guideScreenDesignOpinion.points, guideScreenDesignOpinion = guideScreenDesignOpinion.opinion,
    guideScreenContentPoints = guideScreenContentOpinion.points, guideScreenContentOpinion = guideScreenContentOpinion.opinion,
    guideScreenGeneralPoints = guideScreenGeneralOpinion.points, guideScreenGeneralOpinion = guideScreenGeneralOpinion.opinion,
    menuScreenDesignPoints = menuScreenDesignOpinion.points, menuScreenDesignOpinion = menuScreenDesignOpinion.opinion,
    menuScreenContentPoints = menuScreenContentOpinion.points, menuScreenContentOpinion = menuScreenContentOpinion.opinion,
    menuScreenGeneralPoints = menuScreenGeneralOpinion.points, menuScreenGeneralOpinion = menuScreenGeneralOpinion.opinion,
    loginScreenDesignPoints = loginScreenDesignOpinion.points, loginScreenDesignOpinion = loginScreenDesignOpinion.opinion,
    loginScreenContentPoints = loginScreenContentOpinion.points, loginScreenContentOpinion = loginScreenContentOpinion.opinion,
    loginScreenGeneralPoints = loginScreenGeneralOpinion.points, loginScreenGeneralOpinion = loginScreenGeneralOpinion.opinion,
    signScreenDesignPoints = signScreenDesignOpinion.points, signScreenDesignOpinion = signScreenDesignOpinion.opinion,
    signScreenContentPoints = signScreenContentOpinion.points, signScreenContentOpinion = signScreenContentOpinion.opinion,
    signScreenGeneralPoints = signScreenGeneralOpinion.points, signScreenGeneralOpinion = signScreenGeneralOpinion.opinion,
    homeScreenDesignPoints = homeScreenDesignOpinion.points, homeScreenDesignOpinion = homeScreenDesignOpinion.opinion,
    homeScreenContentPoints = homeScreenContentOpinion.points, homeScreenContentOpinion = homeScreenContentOpinion.opinion,
    homeScreenGeneralPoints = homeScreenGeneralOpinion.points, homeScreenGeneralOpinion = homeScreenGeneralOpinion.opinion,
    settingsScreenDesignPoints = settingsScreenDesignOpinion.points, settingsScreenDesignOpinion = settingsScreenDesignOpinion.opinion,
    settingsScreenContentPoints = settingsScreenContentOpinion.points, settingsScreenContentOpinion = settingsScreenContentOpinion.opinion,
    settingsScreenGeneralPoints = settingsScreenGeneralOpinion.points, settingsScreenGeneralOpinion = settingsScreenGeneralOpinion.opinion,
    profileScreenDesignPoints = profileScreenDesignOpinion.points, profileScreenDesignOpinion = profileScreenDesignOpinion.opinion,
    profileScreenContentPoints = profileScreenContentOpinion.points, profileScreenContentOpinion = profileScreenContentOpinion.opinion,
    profileScreenGeneralPoints = profileScreenGeneralOpinion.points, profileScreenGeneralOpinion = profileScreenGeneralOpinion.opinion,
    chatScreenDesignPoints = chatScreenDesignOpinion.points, chatScreenDesignOpinion = chatScreenDesignOpinion.opinion,
    chatScreenContentPoints = chatScreenContentOpinion.points, chatScreenContentOpinion = chatScreenContentOpinion.opinion,
    chatScreenGeneralPoints = chatScreenGeneralOpinion.points, chatScreenGeneralOpinion = chatScreenGeneralOpinion.opinion,
    groupScreenDesignPoints = groupScreenDesignOpinion.points, groupScreenDesignOpinion = groupScreenDesignOpinion.opinion,
    groupScreenContentPoints = groupScreenContentOpinion.points, groupScreenContentOpinion = groupScreenContentOpinion.opinion,
    groupScreenGeneralPoints = groupScreenGeneralOpinion.points, groupScreenGeneralOpinion = groupScreenGeneralOpinion.opinion,
    playScreenDesignPoints = playScreenDesignOpinion.points, playScreenDesignOpinion = playScreenDesignOpinion.opinion,
    playScreenContentPoints = playScreenContentOpinion.points, playScreenContentOpinion = playScreenContentOpinion.opinion,
    playScreenGeneralPoints = playScreenGeneralOpinion.points, playScreenGeneralOpinion = playScreenGeneralOpinion.opinion,
    mysteryNumberScreenDesignPoints = mysteryNumberScreenDesignOpinion.points, mysteryNumberScreenDesignOpinion = mysteryNumberScreenDesignOpinion.opinion,
    mysteryNumberScreenContentPoints = mysteryNumberScreenContentOpinion.points, mysteryNumberScreenContentOpinion = mysteryNumberScreenContentOpinion.opinion,
    mysteryNumberScreenGeneralPoints = mysteryNumberScreenGeneralOpinion.points, mysteryNumberScreenGeneralOpinion = mysteryNumberScreenGeneralOpinion.opinion,
    wordPassScreenDesignPoints = wordPassScreenDesignOpinion.points, wordPassScreenDesignOpinion = wordPassScreenDesignOpinion.opinion,
    wordPassScreenContentPoints = wordPassScreenContentOpinion.points, wordPassScreenContentOpinion = wordPassScreenContentOpinion.opinion,
    wordPassScreenGeneralPoints = wordPassScreenGeneralOpinion.points, wordPassScreenGeneralOpinion = wordPassScreenGeneralOpinion.opinion,
    quizScreenDesignPoints = quizScreenDesignOpinion.points, quizScreenDesignOpinion = quizScreenDesignOpinion.opinion,
    quizScreenContentPoints = quizScreenContentOpinion.points, quizScreenContentOpinion = quizScreenContentOpinion.opinion,
    quizScreenGeneralPoints = quizScreenGeneralOpinion.points, quizScreenGeneralOpinion = quizScreenGeneralOpinion.opinion,
    familiesScreenDesignPoints = familiesScreenDesignOpinion.points, familiesScreenDesignOpinion = familiesScreenDesignOpinion.opinion,
    familiesScreenContentPoints = familiesScreenContentOpinion.points, familiesScreenContentOpinion = familiesScreenContentOpinion.opinion,
    familiesScreenGeneralPoints = familiesScreenGeneralOpinion.points, familiesScreenGeneralOpinion = familiesScreenGeneralOpinion.opinion,
    surveyScreenDesignPoints = surveyScreenDesignOpinion.points, surveyScreenDesignOpinion = surveyScreenDesignOpinion.opinion,
    surveyScreenContentPoints = surveyScreenContentOpinion.points, surveyScreenContentOpinion = surveyScreenContentOpinion.opinion,
    surveyScreenGeneralPoints = surveyScreenGeneralOpinion.points, surveyScreenGeneralOpinion = surveyScreenGeneralOpinion.opinion,
)
