package es.sebas1705.mappers
/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

import es.sebas1705.common.data.Opinion
import es.sebas1705.common.games.Languages
import es.sebas1705.firestore.documents.SurveyDocument
import es.sebas1705.room.entities.SurveyEntity
import es.sebas1705.youknow.domain.model.stats.SurveyModel

// ENTITY

/**
 * Mapper function
 *
 * @receiver [SurveyEntity]: The object to convert
 *
 * @return [SurveyModel]: The converted object
 *
 * @since 1.0.0
 * @author Sebastián Ramiro Entrerrios García
 */
fun SurveyEntity.toSurveyModel() = SurveyModel(
    authorFirebaseId,
    authorNickName,
    authorAge,
    profession,
    Languages.entries[language],
    androidKnowing,
    applicationsKnowing,
    gamesKnowing,
    socialNetworksKnowing,
    otherKnowing,
    Opinion(predictionPoints, predictionOpinion),
    Opinion(synthesisPoints, synthesisOpinion),
    Opinion(familiarityPoints, familiarityOpinion),
    Opinion(generalityPoints, generalityOpinion),
    Opinion(consistencyPoints, consistencyOpinion),
    Opinion(learnabilityGeneralPoints, learnabilityGeneralOpinion),
    Opinion(dialogInitiativePoints, dialogInitiativeOpinion),
    Opinion(multitaskingPoints, multitaskingOpinion),
    Opinion(taskControlPoints, taskControlOpinion),
    Opinion(adaptationPoints, adaptationOpinion),
    Opinion(substitutionPoints, substitutionOpinion),
    Opinion(flexibilityGeneralPoints, flexibilityGeneralOpinion),
    Opinion(observationCapacityPoints, observationCapacityOpinion),
    Opinion(recuperationCapacityPoints, recuperationCapacityOpinion),
    Opinion(responseCapacityPoints, responseCapacityOpinion),
    Opinion(taskAdaptationPoints, taskAdaptationOpinion),
    Opinion(robustnessGeneralPoints, robustnessGeneralOpinion),
    Opinion(usabilityGeneralPoints, usabilityGeneralOpinion),
    Opinion(equitableUsePoints, equitableUseOpinion),
    Opinion(flexibilityUsePoints, flexibilityUseOpinion),
    Opinion(simpleAndIntuitiveUsePoints, simpleAndIntuitiveUseOpinion),
    Opinion(perceptibleInformationPoints, perceptibleInformationOpinion),
    Opinion(toleranceErrorPoints, toleranceErrorOpinion),
    Opinion(lowPhysicalEffortPoints, lowPhysicalEffortOpinion),
    Opinion(sizeAndSpacePoints, sizeAndSpaceOpinion),
    Opinion(visualProtanopiaPoints, visualProtanopiaOpinion),
    Opinion(visualDeuteranopiaPoints, visualDeuteranopiaOpinion),
    Opinion(visualTritanopiaPoints, visualTritanopiaOpinion),
    Opinion(reducedVisionZoomAdapterPoints, reducedVisionZoomAdapterOpinion),
    Opinion(blindnessScreenReaderPoints, blindnessScreenReaderOpinion),
    Opinion(blindnessElementsSoundPoints, blindnessElementsSoundOpinion),
    Opinion(textInformationPoints, textInformationOpinion),
    Opinion(simpleTextPoints, simpleTextOpinion),
    Opinion(reducedMobilityPoints, reducedMobilityOpinion),
    Opinion(cognitiveSimplePoints, cognitiveSimpleOpinion),
    Opinion(colorSchemeDarkPoints, colorSchemeDarkOpinion),
    Opinion(colorSchemeLightPoints, colorSchemeLightOpinion),
    Opinion(colorSchemeContrastPoints, colorSchemeContrastOpinion),
    Opinion(colorSchemeGeneralPoints, colorSchemeGeneralOpinion),
    Opinion(fontTypeTitlePoints, fontTypeTitleOpinion),
    Opinion(fontTypeBodyPoints, fontTypeBodyOpinion),
    Opinion(fontTypeSpecialPoints, fontTypeSpecialOpinion),
    Opinion(fontTypeGeneralPoints, fontTypeGeneralOpinion),
    Opinion(windowAdaptationPoints, windowAdaptationOpinion),
    Opinion(navigationButtonPoints, navigationButtonOpinion),
    Opinion(navigationBottomBarPoints, navigationBottomBarOpinion),
    Opinion(navigationGeneralPoints, navigationGeneralOpinion),
    Opinion(splashScreenDesignPoints, splashScreenDesignOpinion),
    Opinion(splashScreenGeneralPoints, splashScreenGeneralOpinion),
    Opinion(guideScreenDesignPoints, guideScreenDesignOpinion),
    Opinion(guideScreenContentPoints, guideScreenContentOpinion),
    Opinion(guideScreenGeneralPoints, guideScreenGeneralOpinion),
    Opinion(menuScreenDesignPoints, menuScreenDesignOpinion),
    Opinion(menuScreenContentPoints, menuScreenContentOpinion),
    Opinion(menuScreenGeneralPoints, menuScreenGeneralOpinion),
    Opinion(loginScreenDesignPoints, loginScreenDesignOpinion),
    Opinion(loginScreenContentPoints, loginScreenContentOpinion),
    Opinion(loginScreenGeneralPoints, loginScreenGeneralOpinion),
    Opinion(signScreenDesignPoints, signScreenDesignOpinion),
    Opinion(signScreenContentPoints, signScreenContentOpinion),
    Opinion(signScreenGeneralPoints, signScreenGeneralOpinion),
    Opinion(homeScreenDesignPoints, homeScreenDesignOpinion),
    Opinion(homeScreenContentPoints, homeScreenContentOpinion),
    Opinion(homeScreenGeneralPoints, homeScreenGeneralOpinion),
    Opinion(settingsScreenDesignPoints, settingsScreenDesignOpinion),
    Opinion(settingsScreenContentPoints, settingsScreenContentOpinion),
    Opinion(settingsScreenGeneralPoints, settingsScreenGeneralOpinion),
    Opinion(profileScreenDesignPoints, profileScreenDesignOpinion),
    Opinion(profileScreenContentPoints, profileScreenContentOpinion),
    Opinion(profileScreenGeneralPoints, profileScreenGeneralOpinion),
    Opinion(chatScreenDesignPoints, chatScreenDesignOpinion),
    Opinion(chatScreenContentPoints, chatScreenContentOpinion),
    Opinion(chatScreenGeneralPoints, chatScreenGeneralOpinion),
    Opinion(groupScreenDesignPoints, groupScreenDesignOpinion),
    Opinion(groupScreenContentPoints, groupScreenContentOpinion),
    Opinion(groupScreenGeneralPoints, groupScreenGeneralOpinion),
    Opinion(playScreenDesignPoints, playScreenDesignOpinion),
    Opinion(playScreenContentPoints, playScreenContentOpinion),
    Opinion(playScreenGeneralPoints, playScreenGeneralOpinion),
    Opinion(mysteryNumberScreenDesignPoints, mysteryNumberScreenDesignOpinion),
    Opinion(mysteryNumberScreenContentPoints, mysteryNumberScreenContentOpinion),
    Opinion(mysteryNumberScreenGeneralPoints, mysteryNumberScreenGeneralOpinion),
    Opinion(wordPassScreenDesignPoints, wordPassScreenDesignOpinion),
    Opinion(wordPassScreenContentPoints, wordPassScreenContentOpinion),
    Opinion(wordPassScreenGeneralPoints, wordPassScreenGeneralOpinion),
    Opinion(quizScreenDesignPoints, quizScreenDesignOpinion),
    Opinion(quizScreenContentPoints, quizScreenContentOpinion),
    Opinion(quizScreenGeneralPoints, quizScreenGeneralOpinion),
    Opinion(familiesScreenDesignPoints, familiesScreenDesignOpinion),
    Opinion(familiesScreenContentPoints, familiesScreenContentOpinion),
    Opinion(familiesScreenGeneralPoints, familiesScreenGeneralOpinion),
    Opinion(surveyScreenDesignPoints, surveyScreenDesignOpinion),
    Opinion(surveyScreenContentPoints, surveyScreenContentOpinion),
    Opinion(surveyScreenGeneralPoints, surveyScreenGeneralOpinion)
)

// DOCUMENT

/**
 * Mapper function
 *
 * @receiver [SurveyDocument]: The object to convert
 *
 * @return [SurveyModel]: The converted object
 *
 * @since 1.0.0
 * @author Sebastián Ramiro Entrerrios García
 */
fun SurveyDocument.toSurveyModel() = SurveyModel(
    authorFirebaseId,
    authorNickName,
    authorAge,
    profession,
    Languages.entries[language],
    androidKnowing,
    applicationsKnowing,
    gamesKnowing,
    socialNetworksKnowing,
    otherKnowing,
    Opinion(predictionPoints, predictionOpinion),
    Opinion(synthesisPoints, synthesisOpinion),
    Opinion(familiarityPoints, familiarityOpinion),
    Opinion(generalityPoints, generalityOpinion),
    Opinion(consistencyPoints, consistencyOpinion),
    Opinion(learnabilityGeneralPoints, learnabilityGeneralOpinion),
    Opinion(dialogInitiativePoints, dialogInitiativeOpinion),
    Opinion(multitaskingPoints, multitaskingOpinion),
    Opinion(taskControlPoints, taskControlOpinion),
    Opinion(adaptationPoints, adaptationOpinion),
    Opinion(substitutionPoints, substitutionOpinion),
    Opinion(flexibilityGeneralPoints, flexibilityGeneralOpinion),
    Opinion(observationCapacityPoints, observationCapacityOpinion),
    Opinion(recuperationCapacityPoints, recuperationCapacityOpinion),
    Opinion(responseCapacityPoints, responseCapacityOpinion),
    Opinion(taskAdaptationPoints, taskAdaptationOpinion),
    Opinion(robustnessGeneralPoints, robustnessGeneralOpinion),
    Opinion(usabilityGeneralPoints, usabilityGeneralOpinion),
    Opinion(equitableUsePoints, equitableUseOpinion),
    Opinion(flexibilityUsePoints, flexibilityUseOpinion),
    Opinion(simpleAndIntuitiveUsePoints, simpleAndIntuitiveUseOpinion),
    Opinion(perceptibleInformationPoints, perceptibleInformationOpinion),
    Opinion(toleranceErrorPoints, toleranceErrorOpinion),
    Opinion(lowPhysicalEffortPoints, lowPhysicalEffortOpinion),
    Opinion(sizeAndSpacePoints, sizeAndSpaceOpinion),
    Opinion(visualProtanopiaPoints, visualProtanopiaOpinion),
    Opinion(visualDeuteranopiaPoints, visualDeuteranopiaOpinion),
    Opinion(visualTritanopiaPoints, visualTritanopiaOpinion),
    Opinion(reducedVisionZoomAdapterPoints, reducedVisionZoomAdapterOpinion),
    Opinion(blindnessScreenReaderPoints, blindnessScreenReaderOpinion),
    Opinion(blindnessElementsSoundPoints, blindnessElementsSoundOpinion),
    Opinion(textInformationPoints, textInformationOpinion),
    Opinion(simpleTextPoints, simpleTextOpinion),
    Opinion(reducedMobilityPoints, reducedMobilityOpinion),
    Opinion(cognitiveSimplePoints, cognitiveSimpleOpinion),
    Opinion(colorSchemeDarkPoints, colorSchemeDarkOpinion),
    Opinion(colorSchemeLightPoints, colorSchemeLightOpinion),
    Opinion(colorSchemeContrastPoints, colorSchemeContrastOpinion),
    Opinion(colorSchemeGeneralPoints, colorSchemeGeneralOpinion),
    Opinion(fontTypeTitlePoints, fontTypeTitleOpinion),
    Opinion(fontTypeBodyPoints, fontTypeBodyOpinion),
    Opinion(fontTypeSpecialPoints, fontTypeSpecialOpinion),
    Opinion(fontTypeGeneralPoints, fontTypeGeneralOpinion),
    Opinion(windowAdaptationPoints, windowAdaptationOpinion),
    Opinion(navigationButtonPoints, navigationButtonOpinion),
    Opinion(navigationBottomBarPoints, navigationBottomBarOpinion),
    Opinion(navigationGeneralPoints, navigationGeneralOpinion),
    Opinion(splashScreenDesignPoints, splashScreenDesignOpinion),
    Opinion(splashScreenGeneralPoints, splashScreenGeneralOpinion),
    Opinion(guideScreenDesignPoints, guideScreenDesignOpinion),
    Opinion(guideScreenContentPoints, guideScreenContentOpinion),
    Opinion(guideScreenGeneralPoints, guideScreenGeneralOpinion),
    Opinion(menuScreenDesignPoints, menuScreenDesignOpinion),
    Opinion(menuScreenContentPoints, menuScreenContentOpinion),
    Opinion(menuScreenGeneralPoints, menuScreenGeneralOpinion),
    Opinion(loginScreenDesignPoints, loginScreenDesignOpinion),
    Opinion(loginScreenContentPoints, loginScreenContentOpinion),
    Opinion(loginScreenGeneralPoints, loginScreenGeneralOpinion),
    Opinion(signScreenDesignPoints, signScreenDesignOpinion),
    Opinion(signScreenContentPoints, signScreenContentOpinion),
    Opinion(signScreenGeneralPoints, signScreenGeneralOpinion),
    Opinion(homeScreenDesignPoints, homeScreenDesignOpinion),
    Opinion(homeScreenContentPoints, homeScreenContentOpinion),
    Opinion(homeScreenGeneralPoints, homeScreenGeneralOpinion),
    Opinion(settingsScreenDesignPoints, settingsScreenDesignOpinion),
    Opinion(settingsScreenContentPoints, settingsScreenContentOpinion),
    Opinion(settingsScreenGeneralPoints, settingsScreenGeneralOpinion),
    Opinion(profileScreenDesignPoints, profileScreenDesignOpinion),
    Opinion(profileScreenContentPoints, profileScreenContentOpinion),
    Opinion(profileScreenGeneralPoints, profileScreenGeneralOpinion),
    Opinion(chatScreenDesignPoints, chatScreenDesignOpinion),
    Opinion(chatScreenContentPoints, chatScreenContentOpinion),
    Opinion(chatScreenGeneralPoints, chatScreenGeneralOpinion),
    Opinion(groupScreenDesignPoints, groupScreenDesignOpinion),
    Opinion(groupScreenContentPoints, groupScreenContentOpinion),
    Opinion(groupScreenGeneralPoints, groupScreenGeneralOpinion),
    Opinion(playScreenDesignPoints, playScreenDesignOpinion),
    Opinion(playScreenContentPoints, playScreenContentOpinion),
    Opinion(playScreenGeneralPoints, playScreenGeneralOpinion),
    Opinion(mysteryNumberScreenDesignPoints, mysteryNumberScreenDesignOpinion),
    Opinion(mysteryNumberScreenContentPoints, mysteryNumberScreenContentOpinion),
    Opinion(mysteryNumberScreenGeneralPoints, mysteryNumberScreenGeneralOpinion),
    Opinion(wordPassScreenDesignPoints, wordPassScreenDesignOpinion),
    Opinion(wordPassScreenContentPoints, wordPassScreenContentOpinion),
    Opinion(wordPassScreenGeneralPoints, wordPassScreenGeneralOpinion),
    Opinion(quizScreenDesignPoints, quizScreenDesignOpinion),
    Opinion(quizScreenContentPoints, quizScreenContentOpinion),
    Opinion(quizScreenGeneralPoints, quizScreenGeneralOpinion),
    Opinion(familiesScreenDesignPoints, familiesScreenDesignOpinion),
    Opinion(familiesScreenContentPoints, familiesScreenContentOpinion),
    Opinion(familiesScreenGeneralPoints, familiesScreenGeneralOpinion),
    Opinion(surveyScreenDesignPoints, surveyScreenDesignOpinion),
    Opinion(surveyScreenContentPoints, surveyScreenContentOpinion),
    Opinion(surveyScreenGeneralPoints, surveyScreenGeneralOpinion)
)

// MODEL

/**
 * Mapper function
 *
 * @receiver [SurveyModel]: The object to convert
 *
 * @return [SurveyEntity]: The converted object
 *
 * @since 1.0.0
 * @author Sebastián Ramiro Entrerrios García
 */
fun SurveyModel.toSurveyEntity() = SurveyEntity(
    authorFirebaseId,
    authorNickName,
    authorAge,
    profession,
    language.ordinal,
    androidKnowing,
    applicationsKnowing,
    gamesKnowing,
    socialNetworksKnowing,
    otherKnowing,
    predictionOpinion.points,
    predictionOpinion.opinion,
    synthesisOpinion.points,
    synthesisOpinion.opinion,
    familiarityOpinion.points,
    familiarityOpinion.opinion,
    generalityOpinion.points,
    generalityOpinion.opinion,
    consistencyOpinion.points,
    consistencyOpinion.opinion,
    learnabilityGeneralOpinion.points,
    learnabilityGeneralOpinion.opinion,
    dialogInitiativeOpinion.points,
    dialogInitiativeOpinion.opinion,
    multitaskingOpinion.points,
    multitaskingOpinion.opinion,
    taskControlOpinion.points,
    taskControlOpinion.opinion,
    adaptationOpinion.points,
    adaptationOpinion.opinion,
    substitutionOpinion.points,
    substitutionOpinion.opinion,
    flexibilityGeneralOpinion.points,
    flexibilityGeneralOpinion.opinion,
    observationCapacityOpinion.points,
    observationCapacityOpinion.opinion,
    recuperationCapacityOpinion.points,
    recuperationCapacityOpinion.opinion,
    responseCapacityOpinion.points,
    responseCapacityOpinion.opinion,
    taskAdaptationOpinion.points,
    taskAdaptationOpinion.opinion,
    robustnessGeneralOpinion.points,
    robustnessGeneralOpinion.opinion,
    usabilityGeneralOpinion.points,
    usabilityGeneralOpinion.opinion,
    equitableUseOpinion.points,
    equitableUseOpinion.opinion,
    flexibilityUseOpinion.points,
    flexibilityUseOpinion.opinion,
    simpleAndIntuitiveUseOpinion.points,
    simpleAndIntuitiveUseOpinion.opinion,
    perceptibleInformationOpinion.points,
    perceptibleInformationOpinion.opinion,
    toleranceErrorOpinion.points,
    toleranceErrorOpinion.opinion,
    lowPhysicalEffortOpinion.points,
    lowPhysicalEffortOpinion.opinion,
    sizeAndSpaceOpinion.points,
    sizeAndSpaceOpinion.opinion,
    visualProtanopiaOpinion.points,
    visualProtanopiaOpinion.opinion,
    visualDeuteranopiaOpinion.points,
    visualDeuteranopiaOpinion.opinion,
    visualTritanopiaOpinion.points,
    visualTritanopiaOpinion.opinion,
    reducedVisionZoomAdapterOpinion.points,
    reducedVisionZoomAdapterOpinion.opinion,
    blindnessScreenReaderOpinion.points,
    blindnessScreenReaderOpinion.opinion,
    blindnessElementsSoundOpinion.points,
    blindnessElementsSoundOpinion.opinion,
    textInformationOpinion.points,
    textInformationOpinion.opinion,
    simpleTextOpinion.points,
    simpleTextOpinion.opinion,
    reducedMobilityOpinion.points,
    reducedMobilityOpinion.opinion,
    cognitiveSimpleOpinion.points,
    cognitiveSimpleOpinion.opinion,
    colorSchemeDarkOpinion.points,
    colorSchemeDarkOpinion.opinion,
    colorSchemeLightOpinion.points,
    colorSchemeLightOpinion.opinion,
    colorSchemeContrastOpinion.points,
    colorSchemeContrastOpinion.opinion,
    colorSchemeGeneralOpinion.points,
    colorSchemeGeneralOpinion.opinion,
    fontTypeTitleOpinion.points,
    fontTypeTitleOpinion.opinion,
    fontTypeBodyOpinion.points,
    fontTypeBodyOpinion.opinion,
    fontTypeSpecialOpinion.points,
    fontTypeSpecialOpinion.opinion,
    fontTypeGeneralOpinion.points,
    fontTypeGeneralOpinion.opinion,
    windowAdaptationOpinion.points,
    windowAdaptationOpinion.opinion,
    navigationButtonOpinion.points,
    navigationButtonOpinion.opinion,
    navigationBottomBarOpinion.points,
    navigationBottomBarOpinion.opinion,
    navigationGeneralOpinion.points,
    navigationGeneralOpinion.opinion,
    splashScreenDesignOpinion.points,
    splashScreenDesignOpinion.opinion,
    splashScreenGeneralOpinion.points,
    splashScreenGeneralOpinion.opinion,
    guideScreenDesignOpinion.points,
    guideScreenDesignOpinion.opinion,
    guideScreenContentOpinion.points,
    guideScreenContentOpinion.opinion,
    guideScreenGeneralOpinion.points,
    guideScreenGeneralOpinion.opinion,
    menuScreenDesignOpinion.points,
    menuScreenDesignOpinion.opinion,
    menuScreenContentOpinion.points,
    menuScreenContentOpinion.opinion,
    menuScreenGeneralOpinion.points,
    menuScreenGeneralOpinion.opinion,
    loginScreenDesignOpinion.points,
    loginScreenDesignOpinion.opinion,
    loginScreenContentOpinion.points,
    loginScreenContentOpinion.opinion,
    loginScreenGeneralOpinion.points,
    loginScreenGeneralOpinion.opinion,
    signScreenDesignOpinion.points,
    signScreenDesignOpinion.opinion,
    signScreenContentOpinion.points,
    signScreenContentOpinion.opinion,
    signScreenGeneralOpinion.points,
    signScreenGeneralOpinion.opinion,
    homeScreenDesignOpinion.points,
    homeScreenDesignOpinion.opinion,
    homeScreenContentOpinion.points,
    homeScreenContentOpinion.opinion,
    homeScreenGeneralOpinion.points,
    homeScreenGeneralOpinion.opinion,
    settingsScreenDesignOpinion.points,
    settingsScreenDesignOpinion.opinion,
    settingsScreenContentOpinion.points,
    settingsScreenContentOpinion.opinion,
    settingsScreenGeneralOpinion.points,
    settingsScreenGeneralOpinion.opinion,
    profileScreenDesignOpinion.points,
    profileScreenDesignOpinion.opinion,
    profileScreenContentOpinion.points,
    profileScreenContentOpinion.opinion,
    profileScreenGeneralOpinion.points,
    profileScreenGeneralOpinion.opinion,
    chatScreenDesignOpinion.points,
    chatScreenDesignOpinion.opinion,
    chatScreenContentOpinion.points,
    chatScreenContentOpinion.opinion,
    chatScreenGeneralOpinion.points,
    chatScreenGeneralOpinion.opinion,
    groupScreenDesignOpinion.points,
    groupScreenDesignOpinion.opinion,
    groupScreenContentOpinion.points,
    groupScreenContentOpinion.opinion,
    groupScreenGeneralOpinion.points,
    groupScreenGeneralOpinion.opinion,
    playScreenDesignOpinion.points,
    playScreenDesignOpinion.opinion,
    playScreenContentOpinion.points,
    playScreenContentOpinion.opinion,
    playScreenGeneralOpinion.points,
    playScreenGeneralOpinion.opinion,
    mysteryNumberScreenDesignOpinion.points,
    mysteryNumberScreenDesignOpinion.opinion,
    mysteryNumberScreenContentOpinion.points,
    mysteryNumberScreenContentOpinion.opinion,
    mysteryNumberScreenGeneralOpinion.points,
    mysteryNumberScreenGeneralOpinion.opinion,
    wordPassScreenDesignOpinion.points,
    wordPassScreenDesignOpinion.opinion,
    wordPassScreenContentOpinion.points,
    wordPassScreenContentOpinion.opinion,
    wordPassScreenGeneralOpinion.points,
    wordPassScreenGeneralOpinion.opinion,
    quizScreenDesignOpinion.points,
    quizScreenDesignOpinion.opinion,
    quizScreenContentOpinion.points,
    quizScreenContentOpinion.opinion,
    quizScreenGeneralOpinion.points,
    quizScreenGeneralOpinion.opinion,
    familiesScreenDesignOpinion.points,
    familiesScreenDesignOpinion.opinion,
    familiesScreenContentOpinion.points,
    familiesScreenContentOpinion.opinion,
    familiesScreenGeneralOpinion.points,
    familiesScreenGeneralOpinion.opinion,
    surveyScreenDesignOpinion.points,
    surveyScreenDesignOpinion.opinion,
    surveyScreenContentOpinion.points,
    surveyScreenContentOpinion.opinion,
    surveyScreenGeneralOpinion.points,
    surveyScreenGeneralOpinion.opinion
)

/**
 * Mapper function
 *
 * @receiver [SurveyModel]: The object to convert
 *
 * @return [SurveyDocument]: The converted object
 *
 * @since 1.0.0
 * @author Sebastián Ramiro Entrerrios García
 */
fun SurveyModel.toSurveyDocument() = SurveyDocument(
    authorFirebaseId,
    authorNickName,
    authorAge,
    profession,
    language.ordinal,
    androidKnowing,
    applicationsKnowing,
    gamesKnowing,
    socialNetworksKnowing,
    otherKnowing,
    predictionOpinion.points,
    predictionOpinion.opinion,
    synthesisOpinion.points,
    synthesisOpinion.opinion,
    familiarityOpinion.points,
    familiarityOpinion.opinion,
    generalityOpinion.points,
    generalityOpinion.opinion,
    consistencyOpinion.points,
    consistencyOpinion.opinion,
    learnabilityGeneralOpinion.points,
    learnabilityGeneralOpinion.opinion,
    dialogInitiativeOpinion.points,
    dialogInitiativeOpinion.opinion,
    multitaskingOpinion.points,
    multitaskingOpinion.opinion,
    taskControlOpinion.points,
    taskControlOpinion.opinion,
    adaptationOpinion.points,
    adaptationOpinion.opinion,
    substitutionOpinion.points,
    substitutionOpinion.opinion,
    flexibilityGeneralOpinion.points,
    flexibilityGeneralOpinion.opinion,
    observationCapacityOpinion.points,
    observationCapacityOpinion.opinion,
    recuperationCapacityOpinion.points,
    recuperationCapacityOpinion.opinion,
    responseCapacityOpinion.points,
    responseCapacityOpinion.opinion,
    taskAdaptationOpinion.points,
    taskAdaptationOpinion.opinion,
    robustnessGeneralOpinion.points,
    robustnessGeneralOpinion.opinion,
    usabilityGeneralOpinion.points,
    usabilityGeneralOpinion.opinion,
    equitableUseOpinion.points,
    equitableUseOpinion.opinion,
    flexibilityUseOpinion.points,
    flexibilityUseOpinion.opinion,
    simpleAndIntuitiveUseOpinion.points,
    simpleAndIntuitiveUseOpinion.opinion,
    perceptibleInformationOpinion.points,
    perceptibleInformationOpinion.opinion,
    toleranceErrorOpinion.points,
    toleranceErrorOpinion.opinion,
    lowPhysicalEffortOpinion.points,
    lowPhysicalEffortOpinion.opinion,
    sizeAndSpaceOpinion.points,
    sizeAndSpaceOpinion.opinion,
    visualProtanopiaOpinion.points,
    visualProtanopiaOpinion.opinion,
    visualDeuteranopiaOpinion.points,
    visualDeuteranopiaOpinion.opinion,
    visualTritanopiaOpinion.points,
    visualTritanopiaOpinion.opinion,
    reducedVisionZoomAdapterOpinion.points,
    reducedVisionZoomAdapterOpinion.opinion,
    blindnessScreenReaderOpinion.points,
    blindnessScreenReaderOpinion.opinion,
    blindnessElementsSoundOpinion.points,
    blindnessElementsSoundOpinion.opinion,
    textInformationOpinion.points,
    textInformationOpinion.opinion,
    simpleTextOpinion.points,
    simpleTextOpinion.opinion,
    reducedMobilityOpinion.points,
    reducedMobilityOpinion.opinion,
    cognitiveSimpleOpinion.points,
    cognitiveSimpleOpinion.opinion,
    colorSchemeDarkOpinion.points,
    colorSchemeDarkOpinion.opinion,
    colorSchemeLightOpinion.points,
    colorSchemeLightOpinion.opinion,
    colorSchemeContrastOpinion.points,
    colorSchemeContrastOpinion.opinion,
    colorSchemeGeneralOpinion.points,
    colorSchemeGeneralOpinion.opinion,
    fontTypeTitleOpinion.points,
    fontTypeTitleOpinion.opinion,
    fontTypeBodyOpinion.points,
    fontTypeBodyOpinion.opinion,
    fontTypeSpecialOpinion.points,
    fontTypeSpecialOpinion.opinion,
    fontTypeGeneralOpinion.points,
    fontTypeGeneralOpinion.opinion,
    windowAdaptationOpinion.points,
    windowAdaptationOpinion.opinion,
    navigationButtonOpinion.points,
    navigationButtonOpinion.opinion,
    navigationBottomBarOpinion.points,
    navigationBottomBarOpinion.opinion,
    navigationGeneralOpinion.points,
    navigationGeneralOpinion.opinion,
    splashScreenDesignOpinion.points,
    splashScreenDesignOpinion.opinion,
    splashScreenGeneralOpinion.points,
    splashScreenGeneralOpinion.opinion,
    guideScreenDesignOpinion.points,
    guideScreenDesignOpinion.opinion,
    guideScreenContentOpinion.points,
    guideScreenContentOpinion.opinion,
    guideScreenGeneralOpinion.points,
    guideScreenGeneralOpinion.opinion,
    menuScreenDesignOpinion.points,
    menuScreenDesignOpinion.opinion,
    menuScreenContentOpinion.points,
    menuScreenContentOpinion.opinion,
    menuScreenGeneralOpinion.points,
    menuScreenGeneralOpinion.opinion,
    loginScreenDesignOpinion.points,
    loginScreenDesignOpinion.opinion,
    loginScreenContentOpinion.points,
    loginScreenContentOpinion.opinion,
    loginScreenGeneralOpinion.points,
    loginScreenGeneralOpinion.opinion,
    signScreenDesignOpinion.points,
    signScreenDesignOpinion.opinion,
    signScreenContentOpinion.points,
    signScreenContentOpinion.opinion,
    signScreenGeneralOpinion.points,
    signScreenGeneralOpinion.opinion,
    homeScreenDesignOpinion.points,
    homeScreenDesignOpinion.opinion,
    homeScreenContentOpinion.points,
    homeScreenContentOpinion.opinion,
    homeScreenGeneralOpinion.points,
    homeScreenGeneralOpinion.opinion,
    settingsScreenDesignOpinion.points,
    settingsScreenDesignOpinion.opinion,
    settingsScreenContentOpinion.points,
    settingsScreenContentOpinion.opinion,
    settingsScreenGeneralOpinion.points,
    settingsScreenGeneralOpinion.opinion,
    profileScreenDesignOpinion.points,
    profileScreenDesignOpinion.opinion,
    profileScreenContentOpinion.points,
    profileScreenContentOpinion.opinion,
    profileScreenGeneralOpinion.points,
    profileScreenGeneralOpinion.opinion,
    chatScreenDesignOpinion.points,
    chatScreenDesignOpinion.opinion,
    chatScreenContentOpinion.points,
    chatScreenContentOpinion.opinion,
    chatScreenGeneralOpinion.points,
    chatScreenGeneralOpinion.opinion,
    groupScreenDesignOpinion.points,
    groupScreenDesignOpinion.opinion,
    groupScreenContentOpinion.points,
    groupScreenContentOpinion.opinion,
    groupScreenGeneralOpinion.points,
    groupScreenGeneralOpinion.opinion,
    playScreenDesignOpinion.points,
    playScreenDesignOpinion.opinion,
    playScreenContentOpinion.points,
    playScreenContentOpinion.opinion,
    playScreenGeneralOpinion.points,
    playScreenGeneralOpinion.opinion,
    mysteryNumberScreenDesignOpinion.points,
    mysteryNumberScreenDesignOpinion.opinion,
    mysteryNumberScreenContentOpinion.points,
    mysteryNumberScreenContentOpinion.opinion,
    mysteryNumberScreenGeneralOpinion.points,
    mysteryNumberScreenGeneralOpinion.opinion,
    wordPassScreenDesignOpinion.points,
    wordPassScreenDesignOpinion.opinion,
    wordPassScreenContentOpinion.points,
    wordPassScreenContentOpinion.opinion,
    wordPassScreenGeneralOpinion.points,
    wordPassScreenGeneralOpinion.opinion,
    quizScreenDesignOpinion.points,
    quizScreenDesignOpinion.opinion,
    quizScreenContentOpinion.points,
    quizScreenContentOpinion.opinion,
    quizScreenGeneralOpinion.points,
    quizScreenGeneralOpinion.opinion,
    familiesScreenDesignOpinion.points,
    familiesScreenDesignOpinion.opinion,
    familiesScreenContentOpinion.points,
    familiesScreenContentOpinion.opinion,
    familiesScreenGeneralOpinion.points,
    familiesScreenGeneralOpinion.opinion,
    surveyScreenDesignOpinion.points,
    surveyScreenDesignOpinion.opinion,
    surveyScreenContentOpinion.points,
    surveyScreenContentOpinion.opinion,
    surveyScreenGeneralOpinion.points,
    surveyScreenGeneralOpinion.opinion
)