#!/usr/bin/env bash
# Writes/updates local.properties (what Android Studio reads) with the secrets from Doppler.
#
# Usage:  scripts/doppler-sync-local-properties.sh [project] [config]      (default: youknow dev)
#
# - Only touches the keys the build uses (KEYS); leaves sdk.dir and anything else alone.
# - A key with no value in Doppler keeps whatever local.properties already had.
# - Keys with a value are rewritten in a marked block at the end of the file (and any loose line
#   with that key is removed, so there are no duplicates).
# From the command line this is not needed: `doppler run -- ./gradlew ...` injects the same keys as
# environment variables, which the build reads first (see `secret` in the root build.gradle.kts).
set -euo pipefail

PROJECT="${1:-youknow}"
CONFIG="${2:-dev}"
KEYS=(
  FIREBASE_APP_ID FIREBASE_API_KEY FIREBASE_PROJECT_ID FIREBASE_SENDER_ID
  FIREBASE_STORAGE_BUCKET FIREBASE_DATABASE_URL GOOGLE_WEB_CLIENT_ID
  FIREBASE_APP_ID_PRODUCTION_DEBUG FIREBASE_APP_ID_DEVELOPMENT FIREBASE_APP_ID_DEVELOPMENT_DEBUG
  FIREBASE_APP_ID_STAGING FIREBASE_APP_ID_STAGING_DEBUG
  API_BASE_URL_DEVELOPMENT API_BASE_URL_STAGING API_BASE_URL_PRODUCTION
)

cd "$(dirname "$0")/.."
command -v doppler >/dev/null || { echo "Doppler CLI missing: winget install doppler.doppler" >&2; exit 1; }

touch local.properties
current="$(mktemp)"
block="$(mktemp)"
trap 'rm -f "$current" "$block"' EXIT

# Drop the block generated last time.
sed '/^# >>> doppler/,/^# <<< doppler/d' local.properties > "$current"

synced=0
for key in "${KEYS[@]}"; do
  if value="$(doppler secrets get "$key" --plain -p "$PROJECT" -c "$CONFIG" 2>/dev/null)"; then
    value="${value%$'\r'}" # the CLI on Windows may return CRLF
    if [ -n "$value" ]; then
      printf '%s=%s\n' "$key" "$value" >> "$block"
      sed -i "/^${key}=/d" "$current"
      synced=$((synced + 1))
      continue
    fi
  fi
  echo "  no value in Doppler ($PROJECT/$CONFIG): $key" >&2
done

{
  cat "$current"
  echo "# >>> doppler ($PROJECT/$CONFIG) - generated by scripts/doppler-sync-local-properties.sh, do not edit by hand"
  cat "$block"
  echo "# <<< doppler"
} > local.properties

echo "local.properties updated: $synced key(s) from Doppler ($PROJECT/$CONFIG)."
